### ISSUE TITLE
Big spacing between the lines in menu

### ISSUE THREAD

**Issue by kocio-pl** [osmfoundation/osmf-mediawiki-skin#18]
When the skin is displayed with long menu labels (tested with pl translation), next words are displayed outside the menu bar. Firefox on Ubuntu Bionic (similar effect in Chromium):

![screenshot-2018-4-30 openstreetmap foundation](https://user-images.githubusercontent.com/5439713/39437775-20f72e5e-4ca2-11e8-98f6-812902374002.png)

**Comment by nebulon42** [comment]
Out of curiosity: Have you changed the translation or does the site detect your language preferences?

**Comment by kocio-pl** [comment]
Language was detected.
