### ISSUE TITLE
Font is missing support for nonascii letters

### ISSUE THREAD

**Issue by matkoniecz** [osmfoundation/osmf-mediawiki-skin#30]
some Polish letters are broken - visible due to publishing strategy materials translated into Polish

https://wiki.osmfoundation.org/wiki/Cluster_B_PL is affected

**Comment by matkoniecz** [comment]
Firefox 115.0.2

![screen](https://github.com/osmfoundation/osmf-mediawiki-skin/assets/899988/b053514b-c0ca-4ad2-bd55-d5c6edf75942)

ł ś should now be extra biold

**Comment by Firefishy** [comment]
@matkoniecz Would you mind re-checking? I believe this issue has now been fixed.

**Comment by matkoniecz** [comment]
seems fixed as far as I can see

notified also original reporter who confirmed fix
