### ISSUE TITLE
Disable TOC auto-numbering

### ISSUE THREAD

**Issue by simonpoole** [osmfoundation/osmf-mediawiki-skin#7]
While having auto table of contents generation enabled is a nice feature, the auto-numbering is not, in particular it creates havoc with any kind of formal document with its own numbering, forcing one to turn it completely off, which is kind of not the point.

Unluckily the auto-numbering doesn't seem be able to be turned off on a page by page fashion so likely tuning it off in the skin seems to be the only way forward.

**Comment by nebulon42** [comment]
@simonpoole Just to be clear about what you mean exactly: Could you link to a particular example?

**Comment by nebulon42** [comment]
I guess you meant the Trademark Policy for example.

**Comment by nebulon42** [comment]
Mediawiki suggests doing `<div class="noautonum">__TOC__</div>`
in https://www.mediawiki.org/wiki/Manual:Table_of_contents#Auto-numbering.

**Comment by simonpoole** [comment]
Yes, for example. But anything with its own numbering has the same issue.
